#!/bin/bash

set -e

help() {
    echo "usage: submod clone       clone repositories"
    echo "       submod pull        pull main branch of each repositories"
    echo "       submod dump        dump current commit hashes to submodules.txt"
    echo "       submod update      update commit hashes in submodules.txt"
    echo "       submod help        print this help message"
}

store="submodules"
list="submodules.txt"

# $1 string
# -> name,url,rev
parse_line() {
    local elms=($1)
    name=${elms[0]}
    url=${elms[1]}
    rev=${elms[2]}
}

# Recreate git-tracked symlinks in a repo directory.
# On Windows, git clone produces wrong-type or dangling NTFS reparse points
# because symlink targets don't exist yet at checkout time.  This function
# re-creates every 120000-mode entry using ln -s after all targets are present.
# With MSYS=winsymlinks:nativestrict in the environment, ln -s produces real
# NTFS directory symlinks; on macOS/Linux it is a normal no-op ln -s.
# $1 repo dir (relative to CWD, defaults to .)
fix_symlinks() {
    local proj="${1:-.}"
    while IFS= read -r entry; do
        local hash path target link_path
        hash=$(echo "$entry" | awk '{print $3}')
        path=$(echo "$entry" | awk '{print $4}')
        target=$(git -C "$proj" cat-file blob "$hash")
        link_path="$proj/$path"
        rm -f "$link_path"
        mkdir -p "$(dirname "$link_path")"
        ln -s "$target" "$link_path"
    done < <(git -C "$proj" ls-tree -r HEAD | grep "^120000 ")
}

# $1? project dir
clone() {
    local proj=${1:-.}
    echo "reading $proj/$list"

    # clone
    while read line; do
        parse_line "$line"
        local dir="$store/$name"
        if [[ -e $dir ]]; then
            continue
        fi
        git clone --recursive "$url" "$dir"
        if [[ ! -z "$rev" ]]; then
            git -C "$dir" checkout "$rev"
        fi
    done < "$proj/$list"

    # recursive
    while read line; do
        parse_line "$line"
        local dir="$store/$name"
        if [[ ! -e "$dir/$list" ]]; then
            continue
        fi
        clone "$dir"
        if [[ ! -e "$dir/$store" ]]; then
            # Create relative symlink back to root submodules directory
            # For submodules/foo/submodules -> ../../submodules
            ln -s "../../$store" "$dir/$store"
        fi
    done < "$proj/$list"

    # Recreate all git-tracked symlinks now that their targets exist.
    fix_symlinks "$proj"
}

# $1 dir
dump_line() {
    name="${1##*/}"
    elms=($(git -C "$1" remote -v | grep '(fetch)'))
    url=${elms[1]}
    rev=$(git -C "$1" rev-parse HEAD)
    echo $name $url $rev
}

dump() {
    for dir in "$store"/*; do
        dump_line "$dir" >> "$list.new"
    done
    mv "$list.new" "$list"
    echo "done"
}

update() {
    while read line; do
        parse_line "$line"
        dump_line "$store/$name" >> "$list.new"
    done < "$list"
    mv "$list.new" "$list"
    echo "done"
}

pull() {
    for dir in "$store"/*; do
        git -C "$dir" checkout main || git -C "$dir" checkout master
        git -C "$dir" pull &
    done
    wait
}

$1
